; generated by PrusaSlicer 2.4.0+x64 on 2022-03-14 at 13:47:42 UTC

; 

; external perimeters extrusion width = 0.60mm
; perimeters extrusion width = 0.50mm
; infill extrusion width = 0.50mm
; solid infill extrusion width = 0.50mm
; top infill extrusion width = 0.45mm
; first layer extrusion width = 0.42mm

M73 P0 R4
M73 Q0 S4
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.10.0 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line
G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.

M907 E538 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P1 R4
M73 Q1 S4
G1 Z.2 F720
;AFTER_LAYER_CHANGE
;0.2
M73 P2 R4
M73 Q2 S4
G1 E-.8 F2100
G1 Z.6 F720
G1 X85.515 Y53.693 F10800
G1 Z.2 F720
G1 E.8 F2100
M204 S800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X86.56 Y52.817 E.04278
G1 X87.5 Y52.623 E.03008
G1 X162.5 Y52.623 E2.35157
G1 X163.807 Y53.015 E.04278
M73 P4 R4
M73 Q4 S4
G1 X164.683 Y54.06 E.04278
G1 X164.877 Y55 E.03008
G1 X164.877 Y155 E3.13543
G1 X164.485 Y156.307 E.04278
M73 P6 R3
M73 Q6 S3
G1 X163.44 Y157.183 E.04278
G1 X162.5 Y157.377 E.03008
G1 X87.5 Y157.377 E2.35157
G1 X86.193 Y156.985 E.04278
M73 P7 R3
M73 Q7 S3
G1 X85.317 Y155.94 E.04278
G1 X85.123 Y155 E.03008
G1 X85.123 Y55 E3.13543
M73 Q8 S3
G1 X85.497 Y53.75 E.0409
M204 S1000
; printing object camera-stand.stl id:0 copy 0
;WIPE_START
M73 P9 R3
M73 Q9 S3
G1 F8640
M73 Q10 S3
G1 X86.56 Y52.817 E-.32671
G1 X87.5 Y52.623 E-.22155
G1 X88.417 Y52.623 E-.21174
;WIPE_END
G1 E-.04 F2100
M73 P10 R3
G1 Z.6 F720
G1 X87.91 Y55.41 F10800
G1 Z.2 F720
G1 E.8 F2100
M204 S800
;TYPE:External perimeter
G1 F1200
G1 X162.09 Y55.41 E2.32586
G1 X162.09 Y154.59 E3.10972
M73 P11 R3
M73 Q11 S3
G1 X87.91 Y154.59 E2.32586
M73 P13 R3
M73 Q13 S3
G1 X87.91 Y55.47 E3.10784
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
M106 S84.15
;LAYER_CHANGE
;Z:0.5
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.5


M73 P15 R3
M73 Q15 S3
G1 Z.5 F720
;AFTER_LAYER_CHANGE
;0.5
M73 P16 R3
M73 Q17 S3
G1 E-.8 F2100
M73 P17 R3
G1 Z.9 F720
G1 X85.123 Y55.47 F10800
G1 Z.5 F720
G1 E.8 F2100
;TYPE:Skirt/Brim
G1 F2700
G1 X85.123 Y55 E.02085
G1 X85.515 Y53.693 E.06052
G1 X86.56 Y52.817 E.06052
G1 X87.5 Y52.623 E.04256
G1 X162.5 Y52.623 E3.32661
G1 X163.807 Y53.015 E.06052
G1 X164.683 Y54.06 E.06052
G1 X164.877 Y55 E.04256
G1 X164.877 Y155 E4.43548
G1 X164.485 Y156.307 E.06052
M73 P18 R3
M73 Q18 S3
G1 X163.44 Y157.183 E.06052
G1 X162.5 Y157.377 E.04256
G1 X87.5 Y157.377 E3.32661
G1 X86.193 Y156.985 E.06052
M73 P19 R3
M73 Q19 S3
G1 X85.317 Y155.94 E.06052
G1 X85.123 Y155 E.04256
G1 X85.123 Y55.53 E4.41197
; printing object camera-stand.stl id:0 copy 0
;WIPE_START
G1 F8640
M73 P20 R3
M73 Q20 S3
G1 X85.123 Y55 E-.12238
G1 X85.515 Y53.693 E-.31505
G1 X86.56 Y52.817 E-.31505
G1 X86.592 Y52.81 E-.00752
;WIPE_END
G1 E-.04 F2100
G1 Z.9 F720
G1 X87.8 Y55.53 F10800
G1 Z.5 F720
G1 E.8 F2100
M204 S800
;TYPE:External perimeter
;WIDTH:0.6
G1 X87.8 Y55.3 E.01537
G1 X162.2 Y55.3 E4.97032
G1 X162.2 Y154.7 E6.64046
M73 P21 R3
M73 Q21 S3
G1 X87.8 Y154.7 E4.97032
M73 P22 R3
M73 Q22 S3
G1 X87.8 Y55.59 E6.62108
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
M106 S170.85
;LAYER_CHANGE
;Z:0.8
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.8


M73 P23 R3
M73 Q23 S3
G1 Z.8 F720
;AFTER_LAYER_CHANGE
;0.8
M73 P24 R3
M73 Q24 S3
G1 E-.8 F2100
G1 Z1.2 F720
G1 X85.123 Y55.59 F10800
G1 Z.8 F720
G1 E.8 F2100
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F2700
G1 X85.123 Y55 E.02617
G1 X85.515 Y53.693 E.06052
G1 X86.56 Y52.817 E.06052
G1 X87.5 Y52.623 E.04256
G1 X162.5 Y52.623 E3.32661
G1 X163.807 Y53.015 E.06052
M73 P25 R3
M73 Q25 S3
G1 X164.683 Y54.06 E.06052
G1 X164.877 Y55 E.04256
G1 X164.877 Y155 E4.43548
G1 X164.485 Y156.307 E.06052
M73 P26 R3
M73 Q26 S3
G1 X163.44 Y157.183 E.06052
G1 X162.5 Y157.377 E.04256
G1 X87.5 Y157.377 E3.32661
G1 X86.193 Y156.985 E.06052
M73 P27 R3
M73 Q27 S3
G1 X85.317 Y155.94 E.06052
G1 X85.123 Y155 E.04256
G1 X85.123 Y55.65 E4.40665
; printing object camera-stand.stl id:0 copy 0
;WIPE_START
G1 F8640
M73 Q28 S3
G1 X85.123 Y55 E-.15009
G1 X85.515 Y53.693 E-.31505
G1 X86.493 Y52.873 E-.29486
;WIPE_END
M73 P28 R3
G1 E-.04 F2100
G1 Z1.2 F720
G1 X87.8 Y55.65 F10800
G1 Z.8 F720
G1 E.8 F2100
M204 S800
;TYPE:External perimeter
;WIDTH:0.6
G1 X87.8 Y55.3 E.02338
G1 X162.2 Y55.3 E4.97032
G1 X162.2 Y154.7 E6.64046
M73 P29 R3
M73 Q29 S3
G1 X87.8 Y154.7 E4.97032
M73 P30 R2
M73 Q30 S2
G1 X87.8 Y55.71 E6.61307
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
M106 S255
;LAYER_CHANGE
;Z:1.1
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.1


M73 Q31 S2
G1 Z0.800 F720
;AFTER_LAYER_CHANGE
;1.1
; printing object camera-stand.stl id:0 copy 0
M204 S800
M73 P32 R2
M73 Q32 S2
G1 F1389
G1 Z0.800 X87.8 Y55.3 E0.000
G1 Z0.865 X162.2 Y55.3 E1.070
G1 Z0.950 X162.2 Y154.7 E3.328
M73 P33 R2
M73 Q33 S2
G1 Z1.015 X87.8 Y154.7 E3.555
M73 P35 R2
M73 Q35 S2
G1 Z1.100 X87.8 Y55.71 E6.613
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
;LAYER_CHANGE
;Z:1.4
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.4


M73 P36 R2
M73 Q36 S2
G1 Z1.100 F720
;AFTER_LAYER_CHANGE
;1.4
; printing object camera-stand.stl id:0 copy 0
M204 S800
M73 P38 R2
M73 Q38 S2
G1 F1389
G1 Z1.100 X87.8 Y55.3 E.02739
G1 Z1.165 X162.2 Y55.3 E4.97032
G1 Z1.250 X162.2 Y154.7 E6.64046
M73 P39 R2
M73 Q39 S2
G1 Z1.315 X87.8 Y154.7 E4.97032
M73 P41 R2
M73 Q41 S2
G1 Z1.400 X87.8 Y55.71 E6.61307
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
;LAYER_CHANGE
;Z:1.7
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.7


M73 P42 R2
M73 Q42 S2
G1 Z1.400 F720
;AFTER_LAYER_CHANGE
;1.7
; printing object camera-stand.stl id:0 copy 0
M204 S800
M73 P44 R2
M73 Q44 S2
G1 F1389
G1 Z1.400 X87.8 Y55.3 E.02739
G1 Z1.465 X162.2 Y55.3 E4.97032
G1 Z1.550 X162.2 Y154.7 E6.64046
M73 P45 R2
M73 Q45 S2
G1 Z1.615 X87.8 Y154.7 E4.97032
M73 P47 R2
M73 Q47 S2
G1 Z1.700 X87.8 Y55.71 E6.61307
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
;LAYER_CHANGE
;Z:2
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;2


M73 P48 R2
M73 Q48 S2
G1 Z1.700 F720
;AFTER_LAYER_CHANGE
;2
; printing object camera-stand.stl id:0 copy 0
M204 S800
M73 P49 R2
M73 Q50 S2
G1 F1389
G1 Z1.700 X87.8 Y55.3 E.02739
G1 Z1.765 X162.2 Y55.3 E4.97032
G1 Z1.850 X162.2 Y154.7 E6.64046
M73 P51 R2
M73 Q51 S2
G1 Z1.915 X87.8 Y154.7 E4.97032
M73 P52 R1
M73 Q52 S1
G1 Z2.000 X87.8 Y55.71 E6.61307
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
;LAYER_CHANGE
;Z:2.3
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.3


M73 P54 R1
M73 Q54 S1
G1 Z2.000 F720
;AFTER_LAYER_CHANGE
;2.3
; printing object camera-stand.stl id:0 copy 0
M204 S800
M73 P55 R1
M73 Q55 S1
G1 F1389
G1 Z2.000 X87.8 Y55.3 E.02739
G1 Z2.065 X162.2 Y55.3 E4.97032
G1 Z2.150 X162.2 Y154.7 E6.64046
M73 P57 R1
M73 Q57 S1
G1 Z2.215 X87.8 Y154.7 E4.97032
M73 P58 R1
M73 Q58 S1
G1 Z2.300 X87.8 Y55.71 E6.61307
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
;LAYER_CHANGE
;Z:2.6
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.6


M73 P60 R1
M73 Q60 S1
G1 Z2.300 F720
;AFTER_LAYER_CHANGE
;2.6
; printing object camera-stand.stl id:0 copy 0
M204 S800
M73 P61 R1
M73 Q61 S1
G1 F1389
G1 Z2.300 X87.8 Y55.3 E.02739
G1 Z2.365 X162.2 Y55.3 E4.97032
G1 Z2.450 X162.2 Y154.7 E6.64046
M73 P63 R1
M73 Q63 S1
G1 Z2.515 X87.8 Y154.7 E4.97032
M73 P64 R1
M73 Q64 S1
G1 Z2.600 X87.8 Y55.71 E6.61307
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
;LAYER_CHANGE
;Z:2.9
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.9


M73 P66 R1
M73 Q66 S1
G1 Z2.600 F720
;AFTER_LAYER_CHANGE
;2.9
; printing object camera-stand.stl id:0 copy 0
M204 S800
M73 P67 R1
M73 Q67 S1
G1 F1389
G1 Z2.600 X87.8 Y55.3 E.02739
G1 Z2.665 X162.2 Y55.3 E4.97032
G1 Z2.750 X162.2 Y154.7 E6.64046
M73 P69 R1
M73 Q69 S1
G1 Z2.815 X87.8 Y154.7 E4.97032
M73 P70 R1
M73 Q70 S1
G1 Z2.900 X87.8 Y55.71 E6.61307
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
;LAYER_CHANGE
;Z:3.2
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;3.2


M73 P72 R1
M73 Q72 S1
G1 Z2.900 F720
;AFTER_LAYER_CHANGE
;3.2
; printing object camera-stand.stl id:0 copy 0
M204 S800
M73 P73 R1
M73 Q73 S1
G1 F1389
G1 Z2.900 X87.8 Y55.3 E.02739
G1 Z2.965 X162.2 Y55.3 E4.97032
G1 Z3.050 X162.2 Y154.7 E6.64046
M73 P75 R1
M73 Q75 S1
G1 Z3.115 X87.8 Y154.7 E4.97032
M73 P76 R0
M73 Q76 S0
G1 Z3.200 X87.8 Y55.71 E6.61307
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
;LAYER_CHANGE
;Z:3.5
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;3.5


M73 P78 R0
M73 Q78 S0
G1 Z3.200 F720
;AFTER_LAYER_CHANGE
;3.5
; printing object camera-stand.stl id:0 copy 0
M204 S800
M73 P79 R0
M73 Q79 S0
G1 F1389
G1 Z3.200 X87.8 Y55.3 E.02739
G1 Z3.265 X162.2 Y55.3 E4.97032
G1 Z3.350 X162.2 Y154.7 E6.64046
M73 P81 R0
M73 Q81 S0
G1 Z3.415 X87.8 Y154.7 E4.97032
M73 P82 R0
M73 Q82 S0
G1 Z3.500 X87.8 Y55.71 E6.61307
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
;LAYER_CHANGE
;Z:3.8
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;3.8


M73 P83 R0
M73 Q83 S0
G1 Z3.500 F720
;AFTER_LAYER_CHANGE
;3.8
; printing object camera-stand.stl id:0 copy 0
M204 S800
M73 P85 R0
M73 Q85 S0
G1 F1389
G1 Z3.500 X87.8 Y55.3 E.02739
G1 Z3.565 X162.2 Y55.3 E4.97032
G1 Z3.650 X162.2 Y154.7 E6.64046
M73 P86 R0
M73 Q86 S0
G1 Z3.715 X87.8 Y154.7 E4.97032
M73 P88 R0
M73 Q88 S0
G1 Z3.800 X87.8 Y55.71 E6.61307
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
;LAYER_CHANGE
;Z:4.1
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;4.1


M73 P89 R0
M73 Q89 S0
G1 Z3.800 F720
;AFTER_LAYER_CHANGE
;4.1
; printing object camera-stand.stl id:0 copy 0
M204 S800
M73 P91 R0
M73 Q91 S0
G1 F1389
G1 Z3.800 X87.8 Y55.3 E.02739
G1 Z3.865 X162.2 Y55.3 E4.97032
G1 Z3.950 X162.2 Y154.7 E6.64046
M73 P92 R0
M73 Q92 S0
G1 Z4.015 X87.8 Y154.7 E4.97032
M73 P94 R0
M73 Q94 S0
G1 Z4.100 X87.8 Y55.71 E6.61307
M204 S1000
; stop printing object camera-stand.stl id:0 copy 0
;WIPE_START
M73 P95 R0
M73 Q95 S0
G1 F8640;_WIPE
M73 P97 R0
M73 Q97 S0
G1 X87.8 Y55.3 E-.09467
G1 F8640;_WIPE
G1 X90.681 Y55.3 E-.66533
;WIPE_END
G1 E-.04 F2100
G1 Z4.5 F720
M107
;TYPE:Custom
; Filament-specific end gcode
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z34.1 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 356.53
; filament used [cm3] = 0.86
; filament used [g] = 1.06
; filament cost = 0.03
; total filament used [g] = 1.06
; total filament cost = 0.03
; estimated printing time (normal mode) = 4m 13s
; estimated printing time (silent mode) = 4m 13s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.6
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.5
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 30.24
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_layer_change = 0
; filament_settings_id = "Prusament PLA"
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 0%
; fill_pattern = grid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.5
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 85
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.3
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.5
; perimeter_speed = 50
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.30mm DRAFT @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 30
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.5
; solid_infill_speed = 80
; spiral_vase = 1
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.10.0 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.38
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 45
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 12
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.45
; top_solid_infill_speed = 40
; top_solid_layers = 0
; top_solid_min_thickness = 0.7
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
